### PR TITLE
Feature/vagrant

### PR DESCRIPTION
**Pull request by ReinsBrain**
untested (in Rein's standard form), this group of commits introduces a basic dev environment (node/postgres) and bootstrap to project

### CODE REVIEW

**Comment by ReinsBrain** [comment]
#2 @russormes :: how do we handle pull requests to develop? i think we may need to vote on this stuff which has the advantage of (hopefully) everybody reading and getting familiar with the code base as a whole. Interestingly, I only see Javier, yourself and myself available in the list of collaborators...

**Comment by russormes** [comment]
What does it mean to assign someone to a pull request?

**Comment by russormes** [comment]
Maybe we can use the [pull request review](https://help.github.com/articles/about-pull-request-reviews/) feature for what you are suggesting? We could set it up so it requires as all to give an accepting review before a request can be merged?

**Comment by russormes** [comment]
Edinson has not accepted the invitation and I didn't have Rulo's username on github to invite him. Have requested it now on Slack

**Pull request closed without merging**
